name: tizara
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.24.5"

dependencies:
  after_layout: ^1.2.0
  animate_do: ^3.0.2
  animated_snack_bar: ^0.3.1
  app_popup_menu: ^1.0.0
  awesome_top_snackbar: ^0.0.3
  cached_network_image: ^3.4.0
  calendar_date_picker2: ^0.5.3
  change_app_package_name: ^1.4.0
  cloudflare: ^3.2.1+1
  cloud_firestore: ^4.17.5
  cupertino_icons: ^1.0.2
  custom_refresh_indicator: ^2.2.1
  data_table_2: ^2.2.1
  device_info_plus: ^9.1.2
  dio: ^5.3.2
  dropdown_button2: ^1.9.4
  easy_splash_screen: ^1.0.4
  email_validator: ^2.1.17
  emoji_picker_flutter: ^2.2.0
  fl_chart: ^0.46.0
  flat_list: ^0.1.14
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.0
  flutter_cupertino_datetime_picker: ^3.0.0
  flutter_easyloading: ^3.0.5
  flutter_expandable_fab: ^2.3.0
  flutter_icon_snackbar: ^1.1.4
  flutter_launcher_icons: ^0.14.3
  flutter_local_notifications: ^17.2.4
  flutter_pdfview: ^1.3.4
  flutter_svg: ^1.0.3
  font_awesome_flutter: ^10.7.0
  future_progress_dialog: ^0.2.1
  google_fonts: ^5.0.0
  google_nav_bar: ^5.0.6
  googleapis_auth: ^1.6.0
  http: ^1.0.0
  image_picker: ^1.1.2
  intl: ^0.18.1
  package_info_plus: ^8.1.1
  path_provider: ^2.1.3
  permission_handler: ^10.2.0
  photo_view: ^0.15.0
  provider: ^6.0.2
  shared_preferences: ^2.0.17
  smart_snackbars: ^1.0.0
  url_launcher: ^6.3.1
  win32: ^5.8.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/logo.png"
  adaptive_icon_background: "assets/icon/logo.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
